<!doctype html>

<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BOULEVARD SUL</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" href="View/Page/PageTemplate/css/style.css" type="text/css" media="screen"/>

        <!-- favicon generated by http://realfavicongenerator.net/ -->
        <link rel="apple-touch-icon" sizes="57x57" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-180x180.png">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-194x194.png" sizes="194x194">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/android-chrome-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="View/Page/PageTemplate/img/favicon/manifest.json">
        <link rel="mask-icon" href="View/Page/PageTemplate/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="View/Page/PageTemplate/img/favicon/favicon.ico">
        <meta name="msapplication-TileColor" content="#66e0e5">
        <meta name="msapplication-TileImage" content="View/Page/PageTemplate/img/favicon/mstile-144x144.png">
        <meta name="msapplication-config" content="View/Page/PageTemplate/img/favicon/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
        <!-- end favicon links -->
        <link rel="stylesheet" href="View/Page/PageTemplate/css/bootstrap.min.css" />
        <link rel="stylesheet" href="View/Page/PageTemplate/css/normalize.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/animate.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/flickity.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/styles.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/flexslider.css">
    </head>

    <body>
        <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <section id="index">
            <div class="container-fluid">
                <div class="row">
                    <div class="header-nav-wrapper">
                        <div class="logo">
                            <a href="index.php"><img src="View/Page/PageTemplate/img/boulevardsul.png" alt="Boulevard Sul"></a>
                        </div>
                        <div class="primary-nav-wrapper">
                            <nav>
                                <ul class="primary-nav">
                                    <li><a href="#intro">Boulevard Sul</a></li>
                                    <li><a href="#freebies">Produtos</a></li>
                                    <li><a href="#articles">Novidades</a></li>														
                                </ul>
                            </nav>
                            <div class="secondary-nav-wrapper">
                                <ul class="secondary-nav">
                                    <li class="subscribe"><a href="#contact">Contato</a></li>
                                    <li class="search"><a href="#search" class="show-search"><i class="fa fa-search"></i></a></li>
                                </ul>
                            </div>
                            <div class="search-wrapper">
                                <ul class="search">
                                    <li>
                                        <input type="text" id="search-input" placeholder="Aperte Enter para buscar">
                                    </li>
                                    <li>
                                        <a href="#" class="hide-search"><i class="fa fa-close"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="navicon">
                            <a class="nav-toggle" href="#"><span></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <header>
            <div class="flexslider">
                <ul class="slides">
                    <li>
                        <img src="View/Page/PageTemplate/img/blvd.png" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/andreu.jpg" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/saint.jpg" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/blv_batom.jpg" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/blv_namo.jpg" />
                    </li>
                </ul>
            </div>
            <div class='mouse-container'>
                <a href="#intro">
                    <div class='mouse'>
                        <span class='scroll-down'></span>
                    </div>
                </a>
            </div>
        </header>
        <!-- SECTION: Intro -->
        <section class="collective has-padding" id="intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h4>Boulevard Sul</h4>
                    </div>
                    <div class="col-md-9">
                        <p>
                            A Boulevard Monde chega ao mercado nacional para 
                            apresentar aos consumidores brasileiros uma marca 
                            que conta com profissionais reconhecidos 
                            internacionalmente, que desenvolveram produtos 
                            pioneiros e com tecnologias exclusivas. 
                        </p>
                        <p>
                            Dessa forma, o sucesso da empresa e dos nossos 
                            colaboradores está no comprometimento com a 
                            qualidade dos produtos, logística e respeito ao ser 
                            humano. Desenvolvemos linhas cosméticas, perfumaria 
                            e nutracêuticos que orgulhosamente são inéditos 
                            no Brasil. E esse é só o começo.
                        </p>

                    </div>
                    <div class="col-lg-4" ><!-- Place somewhere in the <body> of your page -->

                    </div>
                </div>
            </div>
        </section>
        <!-- END SECTION: Intro -->

        <!-- SECTION: Stats -->
        <div class="stats has-padding-tall">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4 stats-container">
                        <i class="icon icon-Briefcase"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="24">24</p>
                            <p class="stats-text">Cosméticos</p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 stats-container">
                        <i class="icon icon-Bourbon"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="341">341</p>
                            <p class="stats-text">Perfumes</p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 stats-container">
                        <i class="icon icon-User"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="43">43</p>
                            <p class="stats-text">saúde</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END SECTION: Stats -->

        <!-- SECTION: Freebies -->
        <section class="freebies has-padding" id="freebies">
            <div class="container freebies-intro">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Sobre nós</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 content-left">
                        <p>Uma das características mais marcantes da empresa, 
                            é a criação de uma ambiente de trabalho agradável 
                            e participativo, ouvindo e valorizando seu principal 
                            patrimônio, AS PESSOAS.
                        </p>
                        <p>
                            A Boulevard traz em sua essência a filosofia do 
                            reconhecimento, da meritocracia, onde busca premiar 
                            de forma justa o profissional de Marketing, 
                            valorizando a ética, a moral e as amizades, 
                            tudo isso aliado ao padrão Suíço de gestão.
                        </p>
                    </div>
                    <div class="col-md-6 content-right">
                        <p>
                            Temos nossos objetivos muito bem definidos, 
                            o que nos dá segurança para podermos traçar metas
                            a curto, médio e a longo prazo, sempre trilhando 
                            um caminho sólido e seguro, a fim de oferecer uma 
                            oportunidade a todos aqueles que têm o desejo 
                            de mudar seu panorama financeiro, desenvolvendo 
                            empreendedorismo saudável. 
                        </p>
                        <p>
                            A empresa obedece todas as leis vigentes em nosso 
                            país, e estamos associados a todos os órgãos 
                            competentes.
                        </p>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 no-padding">
                        <article class="item wp5">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class="count">0</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>Perfumes</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=1" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/perfume.jpg" alt="Sedna Freebie Peter Finlan">
                            </figure>
                        </article>
                    </div>
                    <div class="col-md-6 no-padding">
                        <article class="item wp6">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class="count">0</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>Cosméticos</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=2" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/cosmetica.jpg" alt="Land.io Freebie Peter Finlan">
                            </figure>
                        </article>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 no-padding">
                        <article class="item wp7">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class="count">0</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>saúde</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=3" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/saude.jpg" alt="Synthetica Freebie by Peter Finlan">
                            </figure>
                        </article>
                    </div>
                    <div class="col-md-6 no-padding">
                        <article class="item wp8">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class="count">0</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>novidades</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=4" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/fondo.png" alt="Synthetica by Freebie Peter Finlan">
                            </figure>
                        </article>
                    </div>
                    <div class="is-centered">
                        <a href="#index" class="btn secondary view-more"><img src="img/boulevardsulblk.png" alt="Boulevard Sul"></a>
                    </div>
                </div>
            </div>
        </section>
        <!-- END SECTION: Freebies -->

        <!-- SECTION: Get started -->
        <section class="get-started has-padding text-center" id="get-started">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 wp4">
                        <h2>Get started now. Download Synthetica <a href="http://tympanus.net/codrops/?p=26570">FREE</a>, via Codrops.</h2>
                        <a href="http://tympanus.net/codrops/?p=26570" class="btn secondary-white">Get started</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- END SECTION: Get started -->

        <!-- SECTION: Articles -->
        <section class="latest-articles has-padding alternate-bg" id="articles">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <h4>Latest Articles</h4>
                    </div>
                    <div class="col-md-8 col-sm-8 sort">
                        <h5>Sort by</h5>
                        <select name="article-sort" id="inputArticle-Sort" class="">
                            <option value="">Experience Design</option>
                            <option value="">Visual Design</option>
                            <option value="">UI Patterns</option>
                            <option value="">Product Design</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <article class="article-post">
                            <a href="#">
                                <div class="article-image has-overlay" style="background-image: url(View/Page/PageTemplate/img/article-01.jpg)">
                                    <span class="featured-tag">Featured</span>
                                </div>
                                <figure>
                                    <figcaption>
                                        <h2>8 solid tips when working with front-end developers</h2>
                                        <p>A posuere donec senectus suspendisse bibendum magna ridiculus a justo orci parturient suspendisse ad rhoncus...</p>
                                    </figcaption>
                                </figure>
                            </a>
                            <ul class="article-footer">
                                <li class="article-category">
                                    <a href="#">Product</a>
                                </li>
                                <li class="article-comments">
                                    <span><i class="fa fa-comments"></i> 51</span>
                                </li>
                            </ul>
                        </article>
                    </div>
                    <div class="col-md-4">
                        <article class="article-post">
                            <a href="#">
                                <div class="article-image has-overlay" style="background-image: url(View/Page/PageTemplate/img/article-02.jpg)">
                                </div>
                                <figure>
                                    <figcaption>
                                        <h2>The 10 best traits of a awesome design leaders</h2>
                                        <p>A posuere donec senectus suspendisse bibendum magna ridiculus a justo orci parturient suspendisse ad rhoncus...</p>
                                    </figcaption>
                                </figure>
                            </a>
                            <ul class="article-footer">
                                <li class="article-category">
                                    <a href="#">Teams</a>
                                </li>
                                <li class="article-comments">
                                    <span><i class="fa fa-comments"></i> 42</span>
                                </li>
                            </ul>
                        </article>
                    </div>
                    <div class="col-md-4">
                        <article class="article-post">
                            <a href="#">
                                <div class="article-image has-overlay" style="background-image: url(View/Page/PageTemplate/img/article-03.jpg)">
                                </div>
                                <figure>
                                    <figcaption>
                                        <h2>How to design well collaboratively with an agile product team</h2>
                                        <p>A posuere donec senectus suspendisse bibendum magna ridiculus a justo orci parturient suspendisse ad rhoncus...</p>
                                    </figcaption>
                                </figure>
                            </a>
                            <ul class="article-footer">
                                <li class="article-category">
                                    <a href="#">Teams</a>
                                </li>
                                <li class="article-comments">
                                    <span><i class="fa fa-comments"></i> 58</span>
                                </li>
                            </ul>
                        </article>
                    </div>
                </div>
            </div>
            <div class="row is-centered">
                <a href="#freebies" class="btn secondary view-more">Mais Produtos</a>
            </div>
        </section>
        <!-- END SECTION: Articles -->

        <!-- SECTION: Contact -->
        <section class="crew has-padding alternate-bg" id="team">
            <div id="contact">
                <h1>Contate-nos</h1>
                <form id="ContactForm" action="">
                    <p>
                        <label>Nome</label>
                        <input id="name" name="name" class="inplaceError" maxlength="120" type="text" autocomplete="off"/>
                        <span class="error" style="display:none;"></span>
                    </p>
                    <p>
                        <label>Email</label>
                        <input id="email" name="email" class="inplaceError" maxlength="120" type="text" autocomplete="off"/>
                        <span class="error" style="display:none;"></span>
                    </p>
                    <p>
                        <label>Fone<span>(opcional)</span></label>
                        <input id="website" name="website" class="inplaceError" maxlength="120" type="text" autocomplete="off"/>
                    </p>
                    <p>
                        <label>Mensagem<br /> <span>300 caracteres no máximo</span></label>
                        <textarea id="message" name="message" class="inplaceError" cols="6" rows="5" autocomplete="off"></textarea>
                        <span class="error" style="display:none;"></span>
                    </p>
                    <p class="submit">
                        <input id="send" type="button">
                        <span id="loader" class="loader" style="display:none;"></span>
                        <span id="success_message" class="success"></span>
                    </p>
                    <input id="newcontact" name="newcontact" type="hidden" value="1"></input>
                </form>
            </div>
            <div class="envelope">
                <img id="envelope" src="View/Page/PageTemplate/images/envelope.png" alt="envelope" width="246" height="175" style="display:none;"/>
            </div>

            <!-- The JavaScript -->
            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
            <script src="View/Page/PageTemplate/js/jquery.contact.js" type="text/javascript"></script>
            <!--<div class="container">
                    <div class="row">
                            <div class="col-md-12">
                                    <h4>The Crew</h4>
                            </div>
                    </div>
            <!--<div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12">
                            <article class="crew-member" style="background-image: url(img/crew-peter-finlan.jpg)">
                                    <figure>
                                            <figcaption class="overlay">
                                                    <h2>Peter Finlan</h2>
                                                    <p>8-bit aesthetic kitsch 90's humblebrag. Gastropub tacos hoodie letterpress.</p>
                                                    <div class="crew-socials">
                                                            <ul>
                                                                    <li><a href="http://www.twitter.com/peterfinlan/"><i class="fa fa-twitter"></i></a>
                                                                    </li>
                                                                    <li><a href="http://www.linkedin.com/in/peterfinlan/"><i class="fa fa-linkedin"></i></a>
                                                                    </li>
                                                            </ul>
                                                    </div>
                                            </figcaption>
                                    </figure>
                            </article>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                            <article class="crew-member" style="background-image: url(img/crew-blaz-robar.jpg)">
                                    <figure>
                                            <figcaption class="overlay">
                                                    <h2>Blaz Robar</h2>
                                                    <p>8-bit aesthetic kitsch 90's humblebrag. Gastropub tacos hoodie letterpress.</p>
                                                    <div class="crew-socials">
                                                            <ul>
                                                                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                                                                    </li>
                                                                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                                                    </li>
                                                            </ul>
                                                    </div>
                                            </figcaption>
                                    </figure>
                            </article>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                            <article class="crew-member" style="background-image: url(img/crew-mary-lou.jpg)">
                                    <figure>
                                            <figcaption class="overlay">
                                                    <h2>Mary Lou</h2>
                                                    <p>8-bit aesthetic kitsch 90's humblebrag. Gastropub tacos hoodie letterpress.</p>
                                                    <div class="crew-socials">
                                                            <ul>
                                                                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                                                                    </li>
                                                                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                                                    </li>
                                                            </ul>
                                                    </div>
                                            </figcaption>
                                    </figure>
                            </article>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                            <article class="crew-member" style="background-image: url('img/crew-dude.jpg')">
                                    <figure>
                                            <figcaption class="overlay">
                                                    <h2>Kobe West</h2>
                                                    <p>8-bit aesthetic kitsch 90's humblebrag. Gastropub tacos hoodie letterpress.</p>
                                                    <div class="crew-socials">
                                                            <ul>
                                                                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                                                                    </li>
                                                                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                                                    </li>
                                                            </ul>
                                                    </div>
                                            </figcaption>
                                    </figure>
                            </article>
                    </div>
            </div>
            <div class="row skillset">
                    <div class="col-md-6">
                            <div class="bar-chart-wrapper">
                                    <h5 class="bar-chart-text">Experience Design <span class="push-right">90%</span></h5>
                                    <div class="bar-wrapper">
                                            <div class="bar" data-percentage="90%">
                                                    <span></span>
                                            </div>
                                    </div>
                            </div>
                            <div class="bar-chart-wrapper">
                                    <h5 class="bar-chart-text">HTML5/CSS3 <span class="push-right">95%</span></h5>
                                    <div class="bar-wrapper">
                                            <div class="bar" data-percentage="95%">
                                                    <span></span>
                                            </div>
                                    </div>
                            </div>
                    </div>
                    <div class="col-md-6">
                            <div class="bar-chart-wrapper">
                                    <h5 class="bar-chart-text">Interactive Prototyping <span class="push-right">80%</span></h5>
                                    <div class="bar-wrapper">
                                            <div class="bar" data-percentage="80%">
                                                    <span></span>
                                            </div>
                                    </div>
                            </div>
                            <div class="bar-chart-wrapper">
                                    <h5 class="bar-chart-text">Visual Design <span class="push-right">90%</span></h5>
                                    <div class="bar-wrapper">
                                            <div class="bar" data-percentage="90%">
                                                    <span></span>
                                            </div>
                                    </div>
                            </div>
                    </div>
            </div>
    </div>-->
        </section>
        <!-- END SECTION: Crew -->
        <!-- SECTION: Footer -->
        <footer class="has-padding footer-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-branding">
                        <img class="footer-branding-logo" src="View/Page/PageTemplate/img/boulevardsul.png" alt="Synthetica freebie html5 css3 template peter finlan logo">
                        <p>A free HTML5/CSS3 template by <a href="http://www.peterfinlan.com">Peter Finlan</a>, exclusively for <span class="bold-italic">Codrops</span></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 footer-nav">
                        <ul class="footer-primary-nav">
                            <li><a href="#intro">Boulevard Sul</a></li>
                            <li><a href="#freebies">Produtos</a></li>
                            <li><a href="#articles">Novidades</a></li>	
                            <li><a href="#team">Contato</a></li>
                            <li><a href="#">Subscribe</a></li>
                        </ul>
                        <ul class="footer-share">
                            <li><a href="http://tympanus.net/codrops/licensing/">Licence</a></li>
                            <li><a href="#" class="share-trigger"><i class="fa fa-share"></i>Share</a></li>
                        </ul>
                        <div class="share-dropdown">
                            <ul>
                                <li><a href="#" class="share-twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="share-facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="share-linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <ul class="footer-secondary-nav">
                            <li>© Synthetica 2016. A free HTML5/CSS3 Template by <a href="http://www.peterfinlan.com">Peter Finlan</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- END SECTION: Footer -->
        <!-- JS CDNs -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
        <script src="http://vjs.zencdn.net/5.4.6/video.min.js"></script>
        <!-- jQuery local fallback -->
        <script>
            window.jQuery || document.write('<script src="js/min/jquery-1.11.2.min.js"><\/script>')
        </script>
        <!-- JS Locals -->
        <script src="View/Page/PageTemplate/js/min/bootstrap.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/modernizr-2.8.3-respond-1.4.2.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/retina.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/jquery.waypoints.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/flickity.pkgd.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/scripts-min.js"></script>
        <script src="View/Page/PageTemplate/js/jquery.flexslider.js"></script>
        <script type="text/javascript">
            // Can also be used with $(document).ready()
            $(window).load(function () {
                $('.flexslider').flexslider({
                    animation: "slide",
                    controlsContainer: $(".custom-controls-container"),
                    customDirectionNav: $(".custom-navigation a")
                });
            });
        </script>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID and uncomment -->
        <!--
        <script>
        (function(b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l;
                b[l] || (b[l] =
                        function() {
                                (b[l].q = b[l].q || []).push(arguments)
                        });
                b[l].l = +new Date;
                e = o.createElement(i);
                r = o.getElementsByTagName(i)[0];
                e.src = '//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
        ga('create', 'UA-XXXXX-X', 'auto');
        ga('send', 'pageview');
        </script>
        -->
    </body>

</html>
