<!doctype html>

<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BOULEVARD SUL</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" href="View/Page/PageTemplate/css/style.css" type="text/css" media="screen"/>

        <!-- favicon generated by http://realfavicongenerator.net/ -->
        <link rel="apple-touch-icon" sizes="57x57" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="View/Page/PageTemplate/img/favicon/apple-touch-icon-180x180.png">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-194x194.png" sizes="194x194">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/android-chrome-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="View/Page/PageTemplate/img/favicon/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="View/Page/PageTemplate/img/favicon/manifest.json">
        <link rel="mask-icon" href="View/Page/PageTemplate/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="View/Page/PageTemplate/img/favicon/favicon.ico">
        <meta name="msapplication-TileColor" content="#66e0e5">
        <meta name="msapplication-TileImage" content="View/Page/PageTemplate/img/favicon/mstile-144x144.png">
        <meta name="msapplication-config" content="View/Page/PageTemplate/img/favicon/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
        <!-- end favicon links -->
        <link rel="stylesheet" href="View/Page/PageTemplate/css/bootstrap.min.css" />
        <link rel="stylesheet" href="View/Page/PageTemplate/css/normalize.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/animate.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/flickity.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/styles.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="View/Page/PageTemplate/css/flexslider.css">
    </head>

    <body>
        <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <section id="index">
            <div class="container-fluid">
                <div class="row">
                    <div class="header-nav-wrapper">
                        <div class="logo">
                            <a href="index.php"><img src="View/Page/PageTemplate/img/boulevardsul.png" alt="Boulevard Sul"></a>
                        </div>
                        <div class="primary-nav-wrapper">
                            <nav>
                                <ul class="primary-nav">
                                    <li><a href="#intro">Boulevard Sul</a></li>
                                    <li><a href="#freebies">Produtos</a></li>
                                    <li><a href="#articles">Novidades</a></li>														
                                </ul>
                            </nav>
                            <div class="secondary-nav-wrapper">
                                <ul class="secondary-nav">
                                    <li class="subscribe"><a href="#contact">Contato</a></li>
                                    <li class="search"><a href="#search" class="show-search"><i class="fa fa-search"></i></a></li>
                                </ul>
                            </div>
                            <div class="search-wrapper">
                                <ul class="search">
                                    <li>
                                        <input type="text" id="search-input" placeholder="Aperte Enter para buscar">
                                    </li>
                                    <li>
                                        <a href="#" class="hide-search"><i class="fa fa-close"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="navicon">
                            <a class="nav-toggle" href="#"><span></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <header>
            <div class="flexslider">
                <ul class="slides">
                    <li>
                        <img src="View/Page/PageTemplate/img/blvd.png" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/andreu.jpg" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/saint.jpg" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/blv_batom.jpg" />
                    </li>
                    <li>
                        <img src="View/Page/PageTemplate/img/blv_namo.jpg" />
                    </li>
                </ul>
            </div>
            <div class='mouse-container'>
                <a href="#intro">
                    <div class='mouse'>
                        <span class='scroll-down'></span>
                    </div>
                </a>
            </div>
        </header>
        <!-- SECTION: Intro -->
        <section class="collective has-padding" id="intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h4>Boulevard Sul</h4>
                    </div>
                    <div class="col-md-9">
                        <p>
                            A Boulevard Monde chega ao mercado nacional para 
                            apresentar aos consumidores brasileiros uma marca 
                            que conta com profissionais reconhecidos 
                            internacionalmente, que desenvolveram produtos 
                            pioneiros e com tecnologias exclusivas. 
                        </p>
                        <p>
                            Dessa forma, o sucesso da empresa e dos nossos 
                            colaboradores está no comprometimento com a 
                            qualidade dos produtos, logística e respeito ao ser 
                            humano. Desenvolvemos linhas cosméticas, perfumaria 
                            e nutracêuticos que orgulhosamente são inéditos 
                            no Brasil. E esse é só o começo.
                        </p>

                    </div>
                    <div class="col-lg-4" ><!-- Place somewhere in the <body> of your page -->

                    </div>
                </div>
            </div>
        </section>
        <!-- END SECTION: Intro -->

        <!-- SECTION: Stats -->
        <div class="stats has-padding-tall">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 stats-container">
                        <i class="icon icon-User"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="<?php echo $cosmetico[0]['numero'] ?>"></p>
                            <p class="stats-text">Cosméticos</p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 stats-container">
                        <i class="icon icon-Bourbon"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="<?php echo $perfume[0]['numero'] ?>"></p>
                            <p class="stats-text">Perfumes</p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 stats-container">
                        <i class="icon icon-Plaster"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="<?php echo $saude[0]['numero'] ?>"></p>
                            <p class="stats-text">saúde</p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 stats-container">
                        <i class="icon icon-Briefcase"></i>
                        <div class="stats-wrapper">
                            <p class="stats-number" data-stop="<?php echo $make[0]['numero'] ?>"></p>
                            <p class="stats-text">Make Up</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END SECTION: Stats -->

        <!-- SECTION: Freebies -->
        <section class="freebies has-padding" id="freebies">
            <div class="container freebies-intro">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Sobre nós</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 content-left">
                        <p>Uma das características mais marcantes da empresa, 
                            é a criação de uma ambiente de trabalho agradável 
                            e participativo, ouvindo e valorizando seu principal 
                            patrimônio, AS PESSOAS.
                        </p>
                        <p>
                            A Boulevard traz em sua essência a filosofia do 
                            reconhecimento, da meritocracia, onde busca premiar 
                            de forma justa o profissional de Marketing, 
                            valorizando a ética, a moral e as amizades, 
                            tudo isso aliado ao padrão Suíço de gestão.
                        </p>
                    </div>
                    <div class="col-md-6 content-right">
                        <p>
                            Temos nossos objetivos muito bem definidos, 
                            o que nos dá segurança para podermos traçar metas
                            a curto, médio e a longo prazo, sempre trilhando 
                            um caminho sólido e seguro, a fim de oferecer uma 
                            oportunidade a todos aqueles que têm o desejo 
                            de mudar seu panorama financeiro, desenvolvendo 
                            empreendedorismo saudável. 
                        </p>
                        <p>
                            A empresa obedece todas as leis vigentes em nosso 
                            país, e estamos associados a todos os órgãos 
                            competentes.
                        </p>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 no-padding">
                        <article class="item wp5">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class=""><?php echo $perfume[0]['numero'] ?></span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>Perfumes</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=1" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/perfume.jpg" alt="Sedna Freebie Peter Finlan">
                            </figure>
                        </article>
                    </div>
                    <div class="col-md-6 no-padding">
                        <article class="item wp6">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class=""><?php echo $cosmetico[0]['numero'] ?></span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>Cosméticos</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=2" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/Cosmeticos.jpg" alt="Land.io Freebie Peter Finlan">
                            </figure>
                        </article>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 no-padding">
                        <article class="item wp7">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class=""><?php echo $saude[0]['numero'] ?></span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>saúde</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=3" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/saude.jpg" alt="Synthetica Freebie by Peter Finlan">
                            </figure>
                        </article>
                    </div>
                    <div class="col-md-6 no-padding">
                        <article class="item wp8">
                            <figure class="has-overlay">
                                <figcaption class="overlay">
                                    <div class="like-share-wrapper">
                                        <ul>
                                            <li>
                                                <div class="like-button-wrapper">
                                                    <span class=""><?php echo $make[0]['numero'] ?></span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="freebie-content">
                                        <h2>make up</h2>
                                        <div class="group">
                                            <a href="index.php?Controller=PaginaController&Action=portfolio&Tipo=4" class="btn secondary">conteúdo</a>
                                        </div>
                                    </div>
                                </figcaption>
                                <img src="View/Page/PageTemplate/img/Makeup.jpg" alt="Synthetica by Freebie Peter Finlan">
                            </figure>
                        </article>
                    </div>
                    <div class="is-centered">
                        <a href="#index" class="btn secondary view-more"><img src="img/boulevardsulblk.png" alt="Boulevard Sul"></a>
                    </div>
                </div>
            </div>
        </section>
        <!-- END SECTION: Freebies -->

        <!-- SECTION: Get started -->
        <section class="get-started has-padding text-center" id="get-started">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 wp4">
                        <a style="cursor: pointer" id="opor"><h1>OPORTUNIDADE DE NEGOCIO</h1></a>                        
                    </div>
                </div>
            </div>
        </section>
        <!-- END SECTION: Get started -->

        <!-- SECTION: Contact -->
        <section class="crew has-padding alternate-bg" id="team">

            <a id="custom"><i class="fa fa-close"></i></a>
            <div id="contact">
                <h1>Contate-nos</h1>
                <form id="ContactForm" method="POST">
                    <p>
                        <label>Nome</label>
                        <input id="nombre" name="nombre" class="inplaceError" maxlength="120" type="text" autocomplete="off" required/>
                        <span class="error" style="display:none;"></span>
                    </p>
                    <p>
                        <label>Email</label>
                        <input id="email" name="email" class="inplaceError" maxlength="120" type="email" autocomplete="off" required/>
                        <span class="error" style="display:none;"></span>
                    </p>
                    <p>
                        <label>Fone<span>(opcional)</span></label>
                        <input id="telefono" name="telefono" class="inplaceError" maxlength="120" type="text" autocomplete="off"/>
                    </p>
                    <p>
                        <label>Mensagem<br /> <span>300 caracteres no máximo</span></label>
                        <textarea id="texto" name="texto" class="inplaceError" cols="6" rows="5" autocomplete="off" required></textarea>
                        <span class="error" style="display:none;"></span>
                    </p>
                    <p class="submit">
                        <input id="submit" type="submit" name="submit" value="">
                        <span id="loader" class="loader" style="display:none;"></span>
                        <span id="success_message" class="success"></span>
                    </p>

                    <div id="respuesta" style="color: whitesmoke"></div>
                </form>
            </div>
            <div class="envelope">
                <img id="envelope" src="View/Page/PageTemplate/images/envelope.png" alt="envelope" width="246" height="175" style="display:none;"/>
            </div>

            <!-- The JavaScript -->
            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
            <script src="View/Page/PageTemplate/js/jquery.contact.js" type="text/javascript"></script>

        </section>
        <!-- END SECTION: Contact -->

        <!-- SECTION: Articles -->
        <section class="latest-articles has-padding alternate-bg" id="articles">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <h4>Ultimas Noticias</h4>
                    </div>
                    <div class="col-md-8 col-sm-8 sort">

                    </div>
                </div>
                <div class="row">
                    <div id="prev">
                        <?php for ($i = 0; $i < 3; $i++): ?>
                            <div class="col-md-4" id="<?php echo 'blog' . $i; ?>" style="cursor: pointer">
                                <article class="article-post">
                                    <a>
                                        <div class="article-image has-overlay" style="background-image: url(View/Img/Articulos/<?php echo $articulos[$i]['Imagen']; ?>)">
                                        </div>
                                        <figure>
                                            <figcaption>
                                                <h2><?php echo $articulos[$i]['Titulo']; ?></h2>
                                                <p><?php echo $articulos[$i]['Resumen']; ?></p>
                                            </figcaption>
                                        </figure>
                                    </a>
                                    <ul class="article-footer">

                                    </ul>
                                </article>
                            </div>
                        <?php endfor; ?>
                    </div>
                    <?php for ($i = 0; $i < 3; $i++): ?>
                        <div class="col-md-10 col-sm-offset-1" id="<?php echo 'articulo' . $i; ?>">
                            <a class="custom2"><i class="fa fa-close"></i></a>
                            <article class="article-post">
                                <div class="article-image" style="background-image: url(View/Img/Articulos/<?php echo $articulos[$i]['Imagen']; ?>)">
                                </div>
                                <figure>
                                    <figcaption>
                                        <h2><?php echo $articulos[$i]['Titulo']; ?></h2>
                                        <p><?php echo $articulos[$i]['Texto']; ?></p>
                                    </figcaption>
                                </figure>
                                <ul class="article-footer"></ul>
                            </article>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
            <div class="row is-centered">
                <a href="#freebies" class="btn secondary view-more">Mais Produtos</a>
            </div>
        </section>
        <!-- END SECTION: Articles -->

        <!-- SECTION: Footer -->
        <footer class="has-padding footer-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-branding">
                        <img class="footer-branding-logo" src="View/Page/PageTemplate/img/boulevardsul.png" alt="Synthetica freebie html5 css3 template peter finlan logo">

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 footer-nav">
                        <ul class="footer-primary-nav">
                            <li><a href="#intro">Boulevard Sul</a></li>
                            <li><a href="#freebies">Produtos</a></li>
                            <li><a href="#articles">Novidades</a></li>	
                            <li><a href="#team">Contato</a></li>
                            <li><a href="#">Subscribe</a></li>
                        </ul>
                        <ul class="footer-share">
                            <li><a href="http://tympanus.net/codrops/licensing/">Licence</a></li>
                            <li><a href="#" class="share-trigger"><i class="fa fa-share"></i>Share</a></li>
                        </ul>
                        <div class="share-dropdown">
                            <ul>
                                <li><a href="#" class="share-twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="share-facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="share-linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <ul class="footer-secondary-nav">
                            <li>© BoulevardSul 2016. Template by Gary Selios y Moises Lopez</li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- END SECTION: Footer -->
        <!-- JS CDNs -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
        <script src="http://vjs.zencdn.net/5.4.6/video.min.js"></script>
        <!-- jQuery local fallback -->
        <script>
            window.jQuery || document.write('<script src="js/min/jquery-1.11.2.min.js"><\/script>')
        </script>
        <!-- JS Locals -->
        <script src="View/Page/PageTemplate/js/min/bootstrap.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/modernizr-2.8.3-respond-1.4.2.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/retina.min.js"></script>
        <script src="View/Page/PageTemplate/js/min/jquery.waypoints.min.js"></script>
        <script src="View/Page/PageTemplate/js/jquery.flexslider.js"></script>
        <script src="View/Page/PageTemplate/js/min/scripts-min.js"></script>

        <script type="text/javascript">
            // Can also be used with $(document).ready()
            $(window).load(function () {
                $('.flexslider').flexslider({
                    animation: "slide",
                    controlsContainer: $(".custom-controls-container"),
                    customDirectionNav: $(".custom-navigation a")
                });
            });
        </script>
        <script type="text/javascript">
            $(function () {

                $("#team").hide();
                $("#opor").click(function () {
                    $("#team").slideToggle("slow");
                });
                $("#custom").click(function () {
                    $("#team").hide("slow");
                });

                $("#ContactForm").bind("submit", function () {
                    var url = "index.php?Controller=PaginaController&Action=mensaje"; // El script a dónde se realizará la petición.
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: $("#ContactForm").serialize(), // Adjuntar los campos del formulario enviado.
                        success: function (data) {
                            $("#respuesta").html(data); // Mostrar la respuestas del script PHP.
                            $('form')[0].reset();
                        }
                    });
                    return false; // Evitar ejecutar el submit del formulario.
                });

                var a = function () {
                    for (var i = 0; i < 3; i++) {
                        $("#articulo" + i).slideUp();
                    }
                };

                a();

                $("#blog0").click(function () {
                    $("#articulo0").slideToggle('slow');
                    $("#prev").hide('slow');
                });

                $("#blog1").click(function () {
                    $("#articulo1").slideToggle('slow');
                    $("#prev").hide('slow');
                });

                $("#blog2").click(function () {
                    $("#articulo2").slideToggle('slow');
                    $("#prev").hide('slow');
                });

                $(".custom2").click(function () {
                    a();
                    $("#prev").show('slow');
                });

            });
        </script>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID and uncomment -->
        <!--
        <script>
        (function(b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l;
                b[l] || (b[l] =
                        function() {
                                (b[l].q = b[l].q || []).push(arguments)
                        });
                b[l].l = +new Date;
                e = o.createElement(i);
                r = o.getElementsByTagName(i)[0];
                e.src = '//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
        ga('create', 'UA-XXXXX-X', 'auto');
        ga('send', 'pageview');
        </script>
        -->
    </body>

</html>
